include:
 - remote: 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'
 - remote: 'https://gitlab.freedesktop.org/freedesktop/ci-templates/-/raw/34039cd573a2df832d465bc9e4c5f543571f5241/templates/ci-fairy.yml'

stages:
 - build
 - test
 - package

.before_script: &before_script
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .
    - apt-get -y install gcovr

.image: &image
  image:
    name: debian:bookworm

.tags: &tags
  tags:
    - librem5:arm64

# Regular, full build
build:native-debian-bookworm:full:
  <<: *tags
  <<: *image
  <<: *before_script
  stage: build
  artifacts:
    paths:
      - _build
  script:
    - meson -Db_coverage=true --werror . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

# Minimal build for e.g. submodule usage
build:native-debian-bookworm:lib:
  <<: *tags
  <<: *image
  <<: *before_script
  stage: build
  script:
    - meson --werror -Ddaemon=false -Dgtk_doc=false . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

test:native-debian-bookworm:
  <<: *tags
  <<: *image
  <<: *before_script
  stage: test
  needs:
    - build:native-debian-bookworm:full
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  script:
    - dbus-run-session ninja -C _build test coverage
  except:
    variables:
      - $PKG_ONLY == "1"

package:deb-pureos-byzantium:arm64:
  variables:
    L5_DOCKER_IMAGE: pureos/byzantium
  extends: .l5-build-debian-package
  tags:
    - librem5:arm64
