include:
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-definitions.yml'
 - 'https://source.puri.sm/Librem5/librem5-ci/raw/master/librem5-pipeline-bullseye-jobs.yml'

stages:
 - build
 - test
 - package
 - test-package

.before_script: &before_script
  before_script:
    - export DEBIAN_FRONTEND=noninteractive
    - apt-get -y update
    - apt-get -y build-dep .
    - apt-get -y install gcovr

.tags: &tags
  tags:
    - librem5

# Regular, full build
build:native-debian-bullseye:full:
  <<: *tags
  <<: *before_script
  stage: build
  image: debian:bullseye
  artifacts:
    paths:
      - _build
  script:
    - meson -Db_coverage=true --werror . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

# Minimal build for e.g. submodule usage
build:native-debian-bullseye:lib:
  <<: *tags
  <<: *before_script
  stage: build
  image: debian:bullseye
  script:
    - meson --werror -Ddaemon=false -Dgtk_doc=false . _build
    - ninja -C _build
  except:
    variables:
      - $PKG_ONLY == "1"

test:native-debian-bullseye:
  <<: *tags
  <<: *before_script
  stage: test
  image: debian:bullseye
  needs:
    - build:native-debian-bullseye:full
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'
  script:
    - dbus-run-session ninja -C _build test coverage
  except:
    variables:
      - $PKG_ONLY == "1"

